Raise minimum tested compiler from 1.46 to 1.51
Required by use of `resolver` in the `time` crate's Cargo.toml.

    error: failed to download `time v0.3.5`

    Caused by:
      unable to get packages from source

    Caused by:
      failed to parse manifest at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/time-0.3.5/Cargo.toml

    Caused by:
      feature `resolver` is required

      this Cargo does not support nightly features, but if you
      switch to nightly channel you can add
      `cargo-features = ["resolver"]` to enable this feature