Raise minimum supported compiler to rustc 1.46
Required by const fn in bitflags.

    error[E0658]: `if` is not allowed in a `const fn`
      --> /home/david/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.3/src/app/settings.rs:7:1
       |
    7  | / bitflags! {
    8  | |     struct Flags: u64 {
    9  | |         const SC_NEGATE_REQS       = 1;
    10 | |         const SC_REQUIRED          = 1 << 1;
    ...  |
    51 | |     }
    52 | | }
       | |_^
       |
       = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

    error[E0658]: `if` is not allowed in a `const fn`
      --> /home/david/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.3/src/args/settings.rs:6:1
       |
    6  | / bitflags! {
    7  | |     struct Flags: u32 {
    8  | |         const REQUIRED         = 1;
    9  | |         const MULTIPLE         = 1 << 1;
    ...  |
    28 | |     }
    29 | | }
       | |_^
       |
       = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)