Raise required compiler to 1.81
Required by `home` since 0.5.11.

    error: package `home v0.5.11` cannot be built because it requires rustc 1.81 or newer, while the currently active rustc version is 1.74.1
    Either upgrade to rustc 1.81 or newer, or use
    cargo update home@0.5.11 --precise ver
    where `ver` is the latest version of `home` supporting rustc 1.74.1