Raise minimum supported compiler to rustc 1.45
Required by use of str::strip_suffix in `bat`.

    error[E0658]: use of unstable library feature 'str_strip': newly added
       --> /home/david/.cargo/registry/src/github.com-1ecc6299db9ec823/bat-0.18.2/src/assets.rs:304:75
        |
    304 | ...                   if let Some(stripped_filename) = file_str.strip_suffix(suffix) {
        |                                                                 ^^^^^^^^^^^^