Raise required compiler to Rust 1.90
Required by latest release of textwrap.

    error: rustc 1.88.0 is not supported by the following package:
      textwrap@0.16.3 requires rustc 1.90
    Either upgrade rustc or select compatible dependency versions with
    `cargo update <name>@<current-ver> --precise <compatible-ver>`
    where `<compatible-ver>` is the latest version supporting rustc 1.88.0